development:
  adapter: mysql
  encoding: utf8
  database: ballpark_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  encoding: utf8
  database: ballpark_test
  username: root
  password:
  socket: /tmp/mysql.sock